all: Interpreter.java
	javac Interpreter.java
	java Interpreter ../../data/Sample1_IC.txt
	java Interpreter ../../data/Sample2_IC.txt
	java Interpreter ../../data/Sample3_IC.txt
	java Interpreter ../../data/Sample4_IC.txt
	java Interpreter ../../data/Sample5_IC.txt
clean:
	$(RM) Interpreter.class
