all: Interpreter.java
	
	javac Interpreter.java
	# java Interpreter Sample1_IC.txt
	java Interpreter ../0427/Sample5_IC.txt
	java Interpreter ../../Desktop/SER502/Sample1_IC.txt
	java Interpreter ../../Desktop/SER502/Sample2_IC.txt
	java Interpreter ../../Desktop/SER502/Sample3_IC.txt
	java Interpreter ../../Desktop/SER502/Sample4_IC.txt
	java Interpreter ../../Desktop/SER502/Sample5_IC.txt
clean:
	$(RM) Interpreter.class
