compiler: ICGenerator.java
 	  javac ICGenerator.java
	  java ICGenerator ../../data/Sample1.L0
	  java ICGenerator ../../data/Sample2.L0
	  java ICGenerator ../../data/Sample3.L0
	  java ICGenerator ../../data/Sample4.L0
	  java ICGenerator ../../data/Sample5.L0
clean: 
	  $(RM) ICGenerator.class
